### ISSUE TITLE
Using RegReplace on multiple files?

### ISSUE THREAD

**Issue by stephencawood-ai** [facelessuser/RegReplace#10]
Hello and nice work on the plug-in. I have it working, but the use case I'm really after is running multiple find/replace operations on a whole directory.

The Sublime 3 "Find in files" feature includes a 'Where" option which allows me to specify the directory (e.g., "C:\Source\test,*.html"). Can I use this in RegReplace?

Also, can I run multiple find/replace operations with one command?

Thanks again

**Comment by Kristinita** [comment]
@facelessuser , multiple replace in multiple files (even if not use regular expressions) is very good feature. For example, I have to make a lot of changes in many files and this feature will be very useful for me. I hope that someday you will add this feature. 

Thanks.

**Comment by facelessuser** [comment]
@Kristinita, I do understand the desire for this, but it is difficult to justify the work as I just don't work this way with Sublime.  I only use Sublime's single file find in replace, and when I go to do multiple files, I usually use an external tool like [grepWin](http://stefanstools.sourceforge.net/grepWin.html)  which is written in C and very fast (Windows only).  Or I use the tool I wrote (modeled after grepWin) called [Rummage](https://github.com/facelessuser/Rummage) that allows me to use re (with or without backrefs) or the great Python regex library called [regex](https://pypi.python.org/pypi/regex/2016.10.22) (also with or without backrefs) that I use cross platform on Windows, Linux, and OSX.

If my needs require multiple chained regex across an entire project, I usually just write a script.

A lot of my motivation to add features is usually based around my own workflow or my interest in the problem.  The work needed to thread project searching and handling right now is more work than I am currently willing to put in unfortunately. When I am considering features to add to my projects, the feature either has to help me maintain a project better, be something I'll actually use, a trivial feature that doesn't affect my workflow, or just a problem that sounds like fun solving.  As I do all of this in my free time, it usually has to have something compelling for me.

The good news is, there is nothing stopping someone from from writing a plugin that iterates through a project opening files and then running RegReplace commands on them.  It doesn't have to be directly controlled by RegReplace.  I maintain a number of Sublime related projects, I have to be selective on what I do or I'll spend all my time working on Sublime plugins.

But I will keep this in mind in case I ever change my mind.

**Comment by Kristinita** [comment]
>  I only use Sublime's single file find in replace, and when I go to do multiple files, I usually use an external tool like grepWin which is written in C and very fast (Windows only). Or I use the tool I wrote (modeled after grepWin) called Rummage

I not find how I can make multiple replace in multiple files use Rummage. I saw screenshots of Rummage, but I don't saw, how I can make multiple replace in multiple files use Rummage.

Thanks.

**Comment by facelessuser** [comment]
You essentially specify file patterns in `Files which match` using wildcard patterns like `*.html|*.js` etc., but you can also select the regex checkbox and use regex patterns.

You specify the folder to to start the search in  using the `Search in` box.  Make sure to select the `Include subfolders` box to recursively search.  And specify the search pattern in `Search for`.   You specify the replace pattern in `Replace with` (using python regex notation). There are numerous search flags that can be set in the UI.   You can then press the `Search` button which will do just a search to show you what it found.  You press the `Replace` button to actually replace.

I generally recommend people set the file encoding as this is written in Python and encoding detection is slow (and not perfect, but encoding detection never is).  It will be much faster if it doesn't have to detect file encoding.  You can also set it up to show the results in your editor when you double click the file result etc.  I won't go into too much detail here, but if you have more questions, I can answer them.  Just pop on over to the Rummage issues.

Originally there was a guy who translated some the UI interface to Russian (https://github.com/facelessuser/Rummage/blob/master/locale/ru_RU/LC_MESSAGES/rummage.po), but I am fairly certain it is a little out of date at this point as he never pull requested additional updates as the interface changed.  I'd have to go back and see how to enable other languages if you go that route (I don't remember if I documented it at all).  If it seems like a tool you are interested in using, I can refresh myself on the language stuff, but if it seems like something you aren't interested in using, I understand as well.

If you are looking for something a bit faster and you use Windows, grepWin is a great tool as well.  I mainly wrote Rummage to use on OSX and Linux, but I began using it regularly on Windows so I could use the `regex` module's fuzzy regex matching etc., and now I barely use grepWin except when I really need the speed boost (which isn't too often).

Anyways, I'm rambling.  If you have more questions, just jump over to the Rummage repo's issue section.

**Comment by facelessuser** [comment]
Also, you can always just use Sublime's find and replace for multiple files: http://docs.sublimetext.info/en/latest/search_and_replace/search_and_replace_files.html.  Just because I like using an external tool, doesn't mean the internal tool is bad.

**Comment by Kristinita** [comment]
> You specify the folder to to start the search in using the Search in box. Make sure to select the Include subfolders box to recursively search. And specify the search pattern in Search for. You specify the replace pattern in Replace with (using python regex notation). There are numerous search flags that can be set in the UI. You can then press the Search button which will do just a search to show you what it found. You press the Replace button to actually replace.

I understood it 😄 . But how I can make multiple replace in multiple files?

For example, my real example rule for RegReplace, I need replace latin letters to cyrillic:
```json  
        "sasha_felicity_A":
		{
			"find": "A",
			"replace": "А",
		},
		"sasha_felicity_B":
		{
			"find": "B",
			"replace": "В",
		},
	   "sasha_felicity_E":
		{
			"find": "E",
			"replace": "Е",
		},
		"sasha_felicity_K":
		{
			"find": "K",
			"replace": "К",
		},
		"sasha_felicity_M":
		{
			"find": "M",
			"replace": "М",
		},
		"sasha_felicity_H":
		{
			"find": "H",
			"replace": "Н",
		},
		"sasha_felicity_O":
		{
			"find": "O",
			"replace": "О",
		},
		"sasha_felicity_P":
		{
			"find": "P",
			"replace": "Р",
		},
		"sasha_felicity_C":
		{
			"find": "C",
			"replace": "С",
		},
		"sasha_felicity_T":
		{
			"find": "T",
			"replace": "Т",
		},
		"sasha_felicity_a":
		{
			"find": "a",
			"replace": "а",
		},
		"sasha_felicity_e":
		{
			"find": "e",
			"replace": "е",
		},
		"sasha_felicity_o":
		{
			"find": "o",
			"replace": "о",
		},
		"sasha_felicity_p":
		{
			"find": "p",
			"replace": "р",
		},
		"sasha_felicity_c":
		{
			"find": "c",
			"replace": "с",
		},
		"sasha_felicity_y":
		{
			"find": "y",
			"replace": "у",
		},
		"sasha_felicity_x":
		{
			"find": "x",
			"replace": "х",
		},
```

I need print `A` in `Search for:`, print `А` in `Replace with:` and press `Replace`. Than I need print `B` in `Search for:`, print `B` in `Replace with:` and press `Replace`. 18 times, its may take a lot of time.

Use RegReplace I can run all 18 replacement operations run only one command. Is it possible to make the launch of all 18 replacement operations, run only one command, but in multiple files?

Thanks.

**Comment by facelessuser** [comment]
> Use RegReplace I can run all 18 replacement operations run only one command. Is it possible to make the launch of all 18 replacement operations, run only one command, but in multiple files?

I am sorry, I misunderstood.

You are correct, it cannot **currently** do a sequence of replaces.  You can save find and replace patterns in `Save Search` and `Load Search`, but you cannot specify and execute  multiple patterns.  You would still have to load each one.  That is a situation where I would usually write a script at that point, but that is also because I am a programmer (not everyone is who wants to search and replace).  But it is possible I could write a sequencer for Rummage.  I would actually be much more willing to write a sequencer for Rummage than writing a multi file parser RegReplace option.  So this is a possibility.

**Comment by Kristinita** [comment]
> You are correct, it cannot currently do a sequence of replaces. You can save find and replace patterns in Save Search and Load Search, but you cannot specify and execute multiple patterns.

I was not able to find a program to execute multiple patterns for find and replace( . Thanks.

**Comment by facelessuser** [comment]
It is something I'll consider adding in Rummage because I might actually want to use that, but sadly I don't have an immediate solution.
