### ISSUE TITLE
Is there a way to "automate" the linking of multiple rules?

### ISSUE THREAD

**Issue by ceetee13** [facelessuser/RegReplace#101]
I have a situation where I need to replace over three hundred unique pieces of text in a file with different unique names. There is no pattern in the list of what I want to find or in what I want to replace it with.

Eg. I want to replace AF1 with XXX
                                  AF7 with YYY
                                  AF326 with ZZZ
Normally that would require me to do a find and replace in Sublime and copy each name I want to replace with each new name I want. I have managed to join two rules using RegReplace and create a command that runs them correctly. 

This is my code:

```js
{
 "replacements":{
		"1": {
			"find":"AF070931.1",
			"replace":"W1_A1_1_sclerotiorum",
			"greedy": true
		},
		"2": {
			"find":"AF070930.1",
			"replace":"F1_31_L2_sclerotiorum",
			"greedy": true
		}
	} 
}

and the command: 

[
	{
		"caption": "Reg replace AF",
		"command": "reg_replace",
		"args": {
			"replacements": [
				"1",
				"2"
			]
		}
	}
]
```

This runs exactly how I want it to, but in order for me to do this for the remaining 342 unique items I will still have to manually input the rule name, what I want to find and what I want to replace with, which isn't much quicker than manually finding and replacing everything.

Is there a way to list everything I want to find and what I want to replace it without having to manually add a rule for each item? 

Apologies if this has been answered indirectly in previous issues or is in the user documentation, I scanned through both and didn't find anything, but some of the terminology is beyond me.

**Comment by facelessuser** [comment]
There is no automated way to chain all the replacements. With that said, it is possible you could construct a more generic find pattern and use a single replace plugin: http://facelessuser.github.io/RegReplace/usage/#custom-replace-plugins.

The plugin would decide what to replace the find result with.

**Comment by ceetee13** [comment]
Thanks. I've had a look at the custom replace plugins and I have two follow up questions:

Every item I am trying to find starts with AF then has 6 digits, a "." and one more digit (eg. AF070930.1) so I think the find pattern could be more generic. Would the following work?
{
	"AF_replacement":{
		"find": "AF[0-9]*.[0-9]",
		"plugin": "user.single_replace",
		"args": {"some_plugin_arguments": "if_desired"}
	}
}

Then where I'm really stuck is setting up the plugin so that once it finds the first AFXXXXXX it replaces it with the name I want and then the next find result is replaced with the second name and so on. Where would I start with this? 

I assume I would have to define each new name, like how you did with the months in the user guide example. So if the new names I want are W1_A1_1_sclerotiorum, F1_31_L2_sclerotiorum etc. Then I could assign each a number (W1_A1_1_sclerotiorum = 1, F1_31_L2_sclerotiorum = 2 etc.). How would I get the plugin to sequentially replace each name it finds with 1, then 2 then 3 etc.?

**Comment by facelessuser** [comment]
> Every item I am trying to find starts with AF then has 6 digits, a "." and one more digit (eg. AF070930.1) so I think the find pattern could be more generic. Would the following work?

I'd probably be more explicit: `AF[0-9]{6}.[0-9]`, but yeah, it should work.

> Then where I'm really stuck is setting up the plugin so that once it finds the first AFXXXXXX it replaces it with the name I want and then the next find result is replaced with the second name and so on. Where would I start with this?

I'm assuming you just need a dictionary to look up the proper name associated with the number you want to replace.


```python
NAME_MAP = {
    "AF070931.1":  "W1_A1_1_sclerotiorum",
    "AF070930.1":  "F1_31_L2_sclerotiorum"
}


def replace(m):
    # Get the entire name
    name = m.group(0)

    # Get the replacement name in our list, if it isn't found, we will just use the ID that we found
    # essentially replacing nothing.
    return NAME_MAP.get(name, name)
```

Keep in mind I don't fully understand the scope of what you are trying to do, but hopefully this is close to what you want.

**Comment by ceetee13** [comment]
This worked, thank you so much!

**Comment by facelessuser** [comment]
Glad I could help!
