### ISSUE TITLE
Can't create replacement to change smart quotes to dumb quotes

### ISSUE THREAD

**Issue by wave-dash** [facelessuser/RegReplace#106]
## Description

... what is the issue / request ?

I would like to create replacements to change smart quotes to dumb quotes. Here is a working example for single quotes:

```
		"dumb_quotes_single":
		{
			"name": "dumb_quotes_single",
			"find": "[‘’]",
			"replace": "'"
		},
```
However, an equivalent command for double quotes doesn't work because "replace": """ causes an error message.

![2023-04-01_20-55-31_sublime_text_CUsersGregAppDataRoamingSublime_Text_3PackagesUser](https://user-images.githubusercontent.com/8092905/229326848-37e9c429-766f-4e45-a3d0-6dab9dcb6985.png)

## Support Info

...

- ST ver.: 4143
- Platform: windows
- Arch: x64
- Plugin ver.: 3.8.1
- Install via PC: True
- mdpopups ver.: 3.7.5
- backrefs ver.: 5.0
- regex ver.: 2.4.130
- markdown ver.: 3.1.1
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

## Steps to Reproduce Issue

1. Add this to reg_replace_rules.sublime_settings:

```
		"dumb_quotes_double":
		{
			"name": "dumb_quotes_double",
			"find": "[“”]",
			"replace": """
		},
```
2. Save the file.

**Comment by facelessuser** [comment]
You need to respect JSON string requirements. A JSON string must start and end with a double quote. So if you want to put a double quote between them, you need to escape it `\"`.
