### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by rszuster** [facelessuser/RegReplace#29]
I noticed an issue a few days ago, all my "reg_replace" commands disappeared from the command palette and key bindings stopped working as well.
I did some troubleshooting but nothing seemed to help, eventually i installed a fresh copy of Sublime Text and the RegReplace package in a different machine but the behavior is the same.
This is what i found in the console:

Reloading plugin C:\Users\ricardosz\AppData\Roaming\Sublime Text 2\Packages\RegReplace\rr_extended.py
Reloading plugin C:\Users\ricardosz\AppData\Roaming\Sublime Text 2\Packages\RegReplace\rr_notify.py
Reloading plugin C:\Users\ricardosz\AppData\Roaming\Sublime Text 2\Packages\RegReplace\rr_plugin.py
Reloading plugin C:\Users\ricardosz\AppData\Roaming\Sublime Text 2\Packages\RegReplace\rr_replacer.py
Traceback (most recent call last):
File ".\sublime_plugin.py", line 62, in reload_plugin
File ".\rr_replacer.py", line 3, in <module>
from RegReplace.rr_plugin import Plugin
ImportError: No module named RegReplace.rr_plugin
Reloading plugin C:\Users\ricardosz\AppData\Roaming\Sublime Text 2\Packages\RegReplace\rr_sequencer.py
Traceback (most recent call last):
File ".\sublime_plugin.py", line 62, in reload_plugin
File ".\rr_sequencer.py", line 11, in <module>
from RegReplace.rr_replacer import FindReplace
ImportError: No module named RegReplace.rr_replacer

Using ST2 on Windows, tried x64 installer and portable versions with Package Control

**Comment by facelessuser** [comment]
Looks like a recent ST2 release was done from the wrong branch.  This new release (when seen by Package Control) should fix it: [`ST2 1.10.1`](https://github.com/facelessuser/RegReplace/releases/tag/st2-1.10.1).

**Comment by rszuster** [comment]
Awesome, just upgraded the package and it is working again. Thanks !!!
