### ISSUE TITLE
Unable to fold functions

### ISSUE THREAD

**Issue by Bluecakes** [facelessuser/RegReplace#32]
Hello,

RegReplace is amazing, i've got all kinds of keyboard shortcuts to replace phrases but i'm a bit stuck on overriding the action to fold with regex. I use sublime to code in PowerShell so i've modified my regex to adhere to Python regex and i've got it successfully working on regex101 but sadly when i use my keyboard shortcut it says "Fold_functionsv2: 0 regions;"

This is the regex i'm currently working with (regex101 link -> https://www.regex101.com/r/xK7xY0/1)
```
(?:function\s[\w-]+)(.+(?=}\s###\s)}\s###)
```

What i'm trying to achieve is a keyboard shortcut that will fold all functions in the open file so that this
```
function Fold-This
{
    <code here>
} ###

function Fold-That
{
    <code here>
} ###
```
becomes this
```
function Fold-This [...]
function Fold-That [...]
```

I'm using Sublime Text 3 Build 3083 on Windows 8.1 and my settings are as follows

my "replacements" region in reg_replace.sublime-settings

```
    "replacements": {
        // Fold Functions
        "fold_functions": {
            "find" : "(function\\s[\\w-]+)",
            "replace": "",
            "dotall": true
        },
        // Fold Functions v2
        "fold_functionsv2": {
            "find" : "(function\\s[\\w-]+)(.+(?=}\\s###\\s)}\\s###)",
            "replace": "",
            "dotall": true
        },
    },
```

Default.sublime-commands
```
    // Fold Functions
    {
        "caption": "Reg Replace: Fold Functions",
        "command": "reg_replace",
        "args": {"replacements": ["fold_functions"], "action": "fold"}
    },

    // Fold Functions
    {
        "caption": "Reg Replace: Fold Functions",
        "command": "reg_replace",
        "args": {"replacements": ["fold_functionsv2"], "action": "fold"}
    },
```

Default (Windows).sublime-keymap
```
    {
        "keys": ["ctrl+'"],
        "command": "reg_replace",
        "args": {"replacements": ["fold_functions"]}
    },
    {
        "keys": ["ctrl+shift+'"],
        "command": "reg_replace",
        "args": {"replacements": ["fold_functionsv2"]}
    }
```

**Comment by facelessuser** [comment]
I am glad you are having some positive experiences with RegReplace.  I am partial to it :smile:.

Each regex engine is a little different.  Off hand, without trying to run your regex yet, I would think you would need to escape your `}`s.

```
(?:function\s[\w-]+)(.+(?=\}\s###\s)\}\s###)
```

I know it works in your regex101 link, but the regex engine they are using is likely different in regards to this.

If that doesn't help, I will have to wait until I have some time to look further into this.  Folding does work, but you have to get everything just right.  Sadly, not all regex engines are the same.

**Comment by Bluecakes** [comment]
Oh yeah it's brilliant, quite the tiny powerhouse you have created.

I went through the documentation again (Very well written user guide may i say, 10/10 would read again) as i remember an option that will select matching text without replacing to see if my regex is working (Because i susected it wasn't). Knowing that Sublime's Find function is also capable of using regex i tried finding the text between my function just using Sublime and i got an error along the lines of "Found a closing repitition operator } with no corresponding {" so you're definitely right about espacing the parenthesis but sadly after escaping them even Sublime couldn't find any match to my regex.

I don't foresee having much spare time to fiddle with regular expressions in sublime until i finish work in a few hours, when i finish work later today i'll have an hour or two free before my friends also get home so i will definitely play around with it.

If i make any progress i'll be sure to post it and if you do end up looking into a possible regex i could use i would be extremely grateful.

**Comment by facelessuser** [comment]
> but sadly after escaping them even Sublime couldn't find any match to my regex

That's because the sublime find panel doesn't have `dot all`.  You have to explicitly tell it to find every character.  You can do this by saying find whitespace `\s` and non whitespace `\S`.  Also, you don't need a look ahead if you are then right after it looking for the same thing.  And lastly, use a less greedy way of grabbing the content between the functions brackets as `+` will gobble up more than you think; especially when you have two foldable functions after each other; they will be treated as one.  Instead use `+?`.

```
(?:function\s[\w-]+)([\s\S]+?\}\s###)
```

This worked in sublime.  I don't have time tonight to look any further than that, but that should get you on the right path.

**Comment by Bluecakes** [comment]
That regex is a lot more efficient than the one i was trying out in Sublime. Some of the regular expressions i was testing only worked to fold some code but not all, I didn't realize you could use `\s` and `\S` in that way but it does make sense when i think about it. I was able to get it all working the way i want with help from your suggested regex and using the following setup:

```
New Regex -> (###\n\{[\s\S]+?\}\s###)
```

reg_replace.sublime-settings
```
        // Fold Functions
        "fold_functions": {
            "find" : "(###\\n\\{[\\s\\S]+?\\}\\s###)",
            "replace": "",
            "dotall": true
        },
```

Default.sublime-commands
```
    // Fold Functions
    {
        "caption": "Reg Replace: Fold Functions",
        "command": "reg_replace",
        "args": {"replacements": ["fold_functions"], "action": "fold"}
    },
```

Default (Windows).sublime-settings
```
    {
        "keys": ["ctrl+'"],
        "command": "reg_replace",
        "args": {"replacements": ["fold_functions"], "action": "fold"}
    },
```

When pressing `Ctrl + '` it now folds everything between `###`. Many thanks for the assistance, stay awesome and keep up the good work.
