### ISSUE TITLE
Problem with signs replacement

### ISSUE THREAD

**Issue by jakubat** [facelessuser/RegReplace#37]
Dear all,

could you please support me with my Sublime Text 3 setup? 
I'm dealing with a setup which would allow me to remove signs like ( ) , from any text file. 
In order to do so I followed a few tutorials (http://facelessuser.github.io/RegReplace/usage/ or. https://www.sublimetext.com/forum/viewtopic.php?f=5&t=4594)
Please have a look at my settings. It would be great if you could advise me what was done wrong. 
The Reg Replace extension was installed by the Package Manager.

1) Key Bindings - User 
   
   {
	        "keys": ["ctrl+shift+x"],
	        "command": "reg_replace",
	        "args": {"replacements": ["TCL"]}
    }

2) Reg Replace Settings - User 

    {
            "replacements": {
                "TCL": {
                    "find" : "test",
                    "replace": "replaced",
                    "greedy": true,
                    "case": false

                 },
            },
    }

3) Reg Replace Commands - User

    {
        "caption": "Remove TCL brackets",
        "command": "reg_replace",
        "args": {"replacements": ["TCL"]}
    },

The problem is that probably something in the code is not well defined. 
Any of set keys combinations doesn't change the "test" to "replaced"

Thank you in advance for support

Best regards
Jakub

**Comment by facelessuser** [comment]
The following worked fine for me:

In `User/Default.sublime-keymap`

```
{
    "keys": ["ctrl+shift+x"],
    "command": "reg_replace",
    "args": {"replacements": ["TCL"]}
}
```

in `User/reg_replace.sublime-settings`

```
{
    "replacements": {
        "TCL": {
            "find" : "test",
            "replace": "replaced",
            "greedy": true,
            "case": false
        }
    }
}
```

`test` was replaced with `replaced` when I pressed <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>x</kbd>.

I am using ST3.  What version of Sublime are you using?  Do you see errors in your console, and if so, what are they?

**Comment by jakubat** [comment]
I'm using ST3 build 3083.
In the console I can see following message:

"Error loading commands: Error trying to parse file: Unexpected trailing characters in Packages\User\Default.sublime-commands:5:2
reloading Packages/User/reg_replace.sublime-settings
top level value must be an array"

**Comment by jakubat** [comment]
I've just found the problem. A bracket [ ] was missing in the user command file. Thank you for support and help.
