### ISSUE TITLE
Can't match closing brace?

### ISSUE THREAD

**Issue by raray** [facelessuser/RegReplace#38]
I'm trying to write a batch of CSS formatting rules. One of these rules is that a closing curly brace must always have a newline after it. Unfortunately, I cannot seem to find any way to match a closing curly brace at all. Could this just be a bug?

 Here's the replacement I'm trying to get working:
```
// closing brace with no newline after
"css_close_brace_no_newline_after": {
    "find": "}(?!\n)",
    "replace": "}\n",
    "greedy": false,
    "case": false
}
```

**Comment by raray** [comment]
Also not working is matching multiple spaces:
```
"css_mutltiple_spaces": {
    "find": "(\\s+)",
    "replace": " ",
    "greedy": true,
    "case": false
}
```

I apologize is these are user error, but I can run these regexs manually in Sublime and get the desired result.

**Comment by facelessuser** [comment]
This is likely a user error, but before I get involved, I need you to post examples to apply the regex to, and the command you are using as well.  All I see is the regreplace rules.  From my end, I just want to copy and paste what you are using and verify the issue first before I take a closer look.

**Comment by raray** [comment]
I wrote out the entire response showing everything you asked for, and thereby realized that I just forgot that I had to add the reference to the replacements to the command. Thanks for responding. ^_^

**Comment by facelessuser** [comment]
So it's working now?

**Comment by raray** [comment]
Yes. It wasn't running those particular replacements because I hadn't added them to the command.

**Comment by facelessuser** [comment]
Cool, glad you got it working.
