### ISSUE TITLE
Replace in selection

### ISSUE THREAD

**Issue by Engine-X** [facelessuser/RegReplace#44]
I try to create keybindings for surround selection in "console.log()" like this: 
User config: https://upl.io/bljge5 
animation: http://i.imgur.com/KeEmCO0.gifv
What did I do wrong? Why _selection_only_ doesn't work?

**Comment by facelessuser** [comment]
First `selection_only` is not a valid regex rule parameter for replacements, but it is a global settings.  See docs: facelessuser.github.io/RegReplace/usage/#replace-only-under-selections.  See the default settings file: https://github.com/facelessuser/RegReplace/blob/master/reg_replace.sublime-settings#L137.  Maybe this isn't as clear as it could be.

In regreplace you configure regex searches in your setting files under replacements.  You configure patterns, search and replace flags, and things of that kind.  Then you configure a command which is responsible for executing the replacement or chain of replacements.  The command may have parameters and options specifically for the replacement sequence command you construct: maybe you want to highlight searches and prompt the user before replacing, maybe you want to fold those results, etc.

Again, this is covered in the docs: http://facelessuser.github.io/RegReplace/usage/#create-find-and-replace-sequences.

If you are having trouble after reading this response and after reading through the docs, please post your new replacement rules **and** the command you constructed.  Please also elaborate on what exactly you are trying to do as I do not understand from your current description of the problem.

**Comment by Engine-X** [comment]
> Please also elaborate on what exactly you are trying to do as I do not understand from your current description of the problem.
I'm trying to realize wrap any lines or any lines in the selection with console.log(). The second command must return line to its original form. 
In my first example, it works with single lines. Separately, commented and uncomment the line as it should be, but when I try to make these actions with multiple lines in visual selection, it doesn't work. I need to act like with `"greedy": true`, but only in visual selection. 
I'm sorry for the bad description of the problem, I badly speak English

**Comment by facelessuser** [comment]
So, you just want it to apply to each line opposed to just the first line?  Is that what you are looking for?

**Comment by Engine-X** [comment]
Yes, for each line in visual selection

**Comment by facelessuser** [comment]
This worked for me:

```js
        "remove_consolelog": {
            "find": "console\\.log\\((.*?)\\);",
            "replace": "\\1",
            "greedy": true,
            "scope_filter":
            [
                "source.js",
                "-comment", "-!string"
            ]
        },
        "consolelog": {
            "find": "^(.*?)$",
            "replace": "console.log(\\1);",
            "greedy": true,
            "scope_filter":
            [
                "source.js",
                "-comment", "-!string"
            ]
        }
```

Command file:

```js
    {
        "caption": "Replace: Wrap JS console",
        "command": "reg_replace",
        "args": {"replacements": ["consolelog"]}
    },
    {
        "caption": "Replace: Remove JS console",
        "command": "reg_replace",
        "args": {"replacements": ["remove_consolelog"]}
    },
```

**Comment by facelessuser** [comment]
For only applying under a selection, you enable the global `selection_only` setting.  So when you have a selection, it will evaluate text only under the selection, but when there is no selection, it will evaluate the whole file.

**Comment by Engine-X** [comment]
THX, now its work fine, I've read the documentation, but then I did not understand what it means to "global settings", I thought that you can override global settings parameter in "replacements" section.

**Comment by facelessuser** [comment]
Yeah, `selection_only` is just a setting that affects all commands.  It's more of a general behavioral setting.  It's just to allow you to determine if selections are taken into account or not.  Some people just want RegReplace to scan the whole file regardless of what is selected while others want RegReplace to scan **just** selections when available (I prefer the latter).

Glad you got it working.
