### ISSUE TITLE
Replace causes mass amount of NUL to appear

### ISSUE THREAD

**Issue by algorithminflux** [facelessuser/RegReplace#45]
Default.sublime-commands
```
{
        "caption": "Reg Replace: Remove Premature Newlines",
        "command": "reg_replace",
        "args": {"replacements": ["remove_premature_newlines"]}
},
```
reg_replace.sublime-settings
```
"remove_premature_newlines": {
            "find": "\\^(\\.{0,40})\\n",
            "replace": "\\1"
},
```

I'm trying to get this to work. When I use Sublime Text 2's regular Replace feature, the following Find and Replace works like a charm:

Find What: `^(.{0,40})\n`
Replace With: `$1`

This essentially removes the premature newline character from the end of a line. 

However, when I try to translate this into Reg Replace, as depicted at the beginning of this issue, I get the `NUL` character printed between each character. For the life of me, I can't figure what I'm doing wrong. Thanks in advance.

**Comment by facelessuser** [comment]
1.  `^(.{0,40})\n` does not equal `"\\^(\\.{0,40})\\n"`.  Use `"^(\\.{0,40})\\n"`.

2. Check your other plugins as I don't see `NUL` being inserted by this plugin.

**Comment by facelessuser** [comment]
A matter of fact, I see another issue.  Don't use `"^(\\.{0,40})\\n"` either, use "^(.{0,40})\\n"`.

**Comment by facelessuser** [comment]
FYI, I don't directly support Sublime Text 2 anymore, only Sublime Text 3 as noted here: http://facelessuser.github.io/RegReplace/contributing/#overview.  I exclusively use Sublime Text 3 now, and I don't have the time to support ST2 and ST3 on my numerous, available plugins.

**Comment by algorithminflux** [comment]
Hi! Thanks for the quick reply. :)

I tried your regex suggestion in Sublime Text 2, but I got the same result. However, I tried it within Sublime Text 3, and every works like a charm. :) 

Thanks for the support! Very useful plugin.

**Comment by facelessuser** [comment]
That's weird.  Not sure why ST2 would do that, but I am glad ST3 is working.  I use RegReplace all the time, so I try to keep it working well.
