### ISSUE TITLE
An option that allows matching regexes only against the line under the cursor

### ISSUE THREAD

**Issue by Darayavaush** [facelessuser/RegReplace#49]
Right now, if the settings file specifies the selection_only option and nothing is selected, regex gets matched against the entire file, which is undesirable for me. Due to this I would like an additional option along the lines of 'line_match' - if both it and selection_only are true and nothing is selected, then regex gets matched against the current line and not the entire file.

**Comment by facelessuser** [comment]
Why don't you just select the line?

**Comment by Darayavaush** [comment]
Two reasons: 1) I would like to preserve the cursor position, like it is done when regex is matched against the whole file. 2) Creating a macro for every substitution just to select the line before running the replacement feels like a hack.

**Comment by facelessuser** [comment]
The regex only on a line is so specific a use case (one that I rarely use), that I am just not convinced enough to put in the effort.  On the rare occasion I need to specifically search a line, I just select the line.

You may have a very specific use case, but I can't justify the effort for only one person.  It may be in your best interest just to write a simple wrapper plugin that performs the line selection, redirects to reg_replace, and then restores selections afterwards.

Technically, selecting the line is advised solution, but you would like to add this special selection logic specifically for line selections.  What if someone wants to select a paragraph or something else?  I'm just not really interested in opening the doors for lot's of different workflow specific selection logic.  You can easily wrap your special workflow around RegReplace with a simple plugin.  I am providing a tool that can be utilized in your workflow, but not specifically a solution to that will out of the box provide a solution to all workflows.

**Comment by Darayavaush** [comment]
Hm, you're right. I was misremembering this as default behaviour of Find and Replace in ST, and would be thus worthy of inclusion for standartization purposes, but it appears it's not the case. All right, I guess I'll indeed consider writing a plugin for my needs, Thanks for the idea. :)
