### ISSUE TITLE
[Question] I can not to make simple replacement

### ISSUE THREAD

**Issue by Kristinita** [facelessuser/RegReplace#50]
### Summary

I can not begin to use RegReplace. No replacements for me.

### Expected behavior

Multiple replacements.

### Actual behavior

`command: reg_replace {"replacements": ["sublime_h", "sublime_r"]}`

But no replacements.

### Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I install RegReplace.

`Preferences` → `Package Settings` → `RegReplace` → `Settings - User` → I paste and save code:

```json
{
    "replacements":
    {
        "sublime_h":
        {
            "find": "h",
            "replace": "f",
            "greedy": true,
            "case": false
        },
        "sublime_r":
        {
            "find": "r",
            "replace": "u",
            "greedy": true,
            "case": false
        }
    }
}

```

`Preferences` → `Package Settings` → `RegReplace` → `Commands - User` → I paste and save code:

```json
[
    {
      "caption": "Reg Replace: Test RegReplace",
      "command": "reg_replace",
      "args": {
        "replacements": [
          "sublime_h",
          "sublime_r"
        ],
      }
    },
]

```

I create file `test.md`:

    h r

In `test.md` file I press <kbd>Ctrl+Shift+P</kbd> → `Reg Replace: Test RegReplace` → but I have not replacements `h`→ `f`, `r` → `u`.

What I do wrong?

### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by facelessuser** [comment]
Are you using an old version?  Maybe you looked at past issues and are using outdated info?

1. Rules go in `reg_replace_rules.sublime-settings`.  You can get there by:

    `Preferences` → `Package Settings` → `RegReplace` → `Rules - User`.

2. `case` is no longer a valid option.  If you want case insensitivity, you use the Python regex notation: `(?i)`. Example: http://stackoverflow.com/a/10444271.  Official docs: https://docs.python.org/2/library/re.html.

```
{
       "format": "3.0",
       "sublime_h":
        {
            "find": "(?i)h",
            "replace": "f",
            "greedy": true
        },
        "sublime_r":
        {
            "find": "(?i)r",
            "replace": "u",
            "greedy": true
        }
}
```

and

```js
[
    {
      "caption": "Reg Replace: Test RegReplace",
      "command": "reg_replace",
      "args": {
        "replacements": [
          "sublime_h",
          "sublime_r"
        ]
      }
    }
]
```

This worked fine for me.

**Comment by Kristinita** [comment]
> Are you using an old version? Maybe you looked at past issues and are using outdated info?

I use examples of article [Run Multiple Find & Replace Commands in Sublime Text](https://css-tricks.com/run-multiple-find-replace-commands-sublime-text/) of June 7, 2016. I did not think that the article is outdated.

Correct syntax is:

```json
{
    "replacements":
	{
	   "sublime_h":
		{
			"find": "(?i)h",
			"replace": "f",
			"greedy": true
		},
		"sublime_r":
		{
			"find": "(?i)r",
			"replace": "u",
			"greedy": true
		}
	}
}
```

It works fine for me.

Thank you very much!

**Comment by facelessuser** [comment]
You're welcome.
