### ISSUE TITLE
RegReplace no longer available/installable in SublimeText 3

### ISSUE THREAD

**Issue by regularlabs** [facelessuser/RegReplace#51]
Hope you can help me with this.
Don't know if this is due to some change in SublimeText 3 or something else:

Since today (maybe longer) I do not have RegReplace in the installed packages anymore.
The setting files are still there, but it isn't listed under the packages.
I tried deleting the RegReplace files and reinstalling it. But it seems nothing happens.
So RegReplace isn't working anymore...

**Comment by regularlabs** [comment]
Solved by deleting file `/Library/Application Support/Sublime Text 3/Installed Packages/0_package_control_loader.sublime-package`
And restarting and reinstalling RegReplace.

**Comment by facelessuser** [comment]
Okay, so I guess it was a Package Control issue.  Must have been some weird corner case.  Well I am glad you got it working.

**Comment by regularlabs** [comment]
Yep, thanks.

PS: Love RegReplace :)
Not surprising, seeing I made this: https://www.regularlabs.com/extensions/rereplacer
Pretty much RegReplace for Joomla, first version from back in 2008! (boy, I'm getting old)

**Comment by facelessuser** [comment]
> PS: Love RegReplace :)
Not surprising, seeing I made this: https://www.regularlabs.com/extensions/rereplacer
Pretty much RegReplace for Joomla, first version from back in 2008! (boy, I'm getting old)

Lol.  Thanks!  That's awesome :).
