### ISSUE TITLE
In several files "teh" is used instead of "the"

### ISSUE THREAD

**Issue by MaxValue** [facelessuser/RegReplace#53]
## Description
In several files "teh" is used instead of "the".

## Steps to Reproduce Issue
1. Go to this repository.
2. Enter "teh" into the search bar.
3. See all the files where that typo occurs.

**Comment by facelessuser** [comment]
Yeah, fast fingers always screwing up what the brain is thinking. That is a common mistake I make when typing (obviously).  I should really run a spell checker on my docs via CI to keep me from pushing out my sloppy ramblings.

Thanks for the heads up.

**Comment by facelessuser** [comment]
Note:

Add a Travis CI entry to build docs and perform spellchecking via aspell.  This work is already done on another repo.  Just needs to be integrated here.
