### ISSUE TITLE
Missing example file mentioned in User Guide

### ISSUE THREAD

**Issue by Asuza** [facelessuser/RegReplace#59]
Under _Custom Replace Plugins_ in the [user guide](https://facelessuser.github.io/RegReplace/usage/#custom-replace-plugins), it mentions:
>RegReplace comes with a very simple example you can test with found at `/Packages/RegReplace/rr_modules/example.py`.

However, I couldn't find that file. I assume it's because I installed it via Package Control instead of manually, but I'm not certain. In my case, there is no _/Packages/RegReplace_ directory. Rather, I have _/Installed Packages/RegReplace.sublime-package_.

I don't need the file now, but it might be confusing to others.

**Comment by facelessuser** [comment]
It's not really an error, Package control zips packages in `Installed Packages`, but via the API, you access them as if they are in `Packages`.

**Comment by Asuza** [comment]
Don't you have to have knowledge of how packages work before you could easily find the example file? As far as I know, you would still have to extract it from the sublime-package file and put it in the correct location.

I thought that perhaps at some point in time, the plug-in was **not** compressed and therefore at the time, the documentation was correct.

I just wanted to let you know so it could be made simpler for people without knowledge of the package system.

**Comment by facelessuser** [comment]
I agree I could reference the file directly on the repo instead of referencing it in relation to package installation to make it clearer, but to include it, the documents are still correct: `RegReplace.rr_modules.example`.

**Comment by Asuza** [comment]
I don't understand how you would easily view `example.py` to see what it actually does, though.

**Comment by facelessuser** [comment]
I agree that the documentation doesn't help you easily know what to do.  Currently you could look at the actual [repository](https://github.com/facelessuser/RegReplace/blob/master/rr_modules/example.py) or use PackageResourceViewer plugin to view it.  But the documentation should be updated to explain this better, and I should probably add a menu option that will open it directly through the API for viewing purposes.

**Comment by facelessuser** [comment]
Or I could just post the example snippet directly in the documentation.
