### ISSUE TITLE
Warn when a rule isn't found

### ISSUE THREAD

**Issue by Asuza** [facelessuser/RegReplace#60]
## Feature request

Please provide some kind of warning message or console error when a rule needed by a command is not found.

I copied my _reg_replace_rules.sublime-settings_ file from one machine to another, accidentally naming it _reg_replace.sublime-settings_ in the process. None of my rules were accessible at that point, but I didn't realize what the problem was. Nothing seemed wrong in the Sublime console, and I could technically "run" any of the rules I'd made, but no replacements would be made.

The same thing happens when misspelling a rule name.

## Support Info
- ST ver.: 3131
- Platform: linux
- Arch: x64
- Plugin ver.: 3.2.1
- Install via PC: True
- mdpopups ver.: 1.13.1
- backrefs ver.: 1.0.post1
- regex ver.: 2.4.112
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

**Comment by facelessuser** [comment]
I'll take a look when I get some time.  Seems reasonable.
