### ISSUE TITLE
Sublime Text Command Not showing up for Command Palette 

### ISSUE THREAD

**Issue by davidfufu** [facelessuser/RegReplace#64]
I copied and pasted the example code from the documentation, but I don't see the command when I open up command palette.

In my, Default.sublime.commands, I have only this code:
`    {

        "caption": "Reg Replace: Remove Trailing Spaces",

        "command": "reg_replace",

        "args": {"replacements": ["trailing_spaces"]}

    }
`

Within reg_replace_rules, I have only this:

`{

	"replacements":

	{

		"trailing_spaces":

		{

			"find": "[\\t]+$",
			"name": "trailing_spaces",
			"replace": ""

		}
	}
}
`
It is my understanding that this is enough to execute the replacement. The rule has been defined and the command has been created to launch it. But when I do Shift+ctrl+P, I only see the basic edit, create, delete/and the paths to the regreplace settings files.

The documentation was a bit unclear on how to actually RUN the replacement and I didn't really see any continuity between the example defining the two example replacement rules with the 3 different ways to create the command/make a hotkey.

I then added this to my keymap file.
`	{

		"keys": ["alt+shift+t"],

		"command": "reg_replace",

		"args": {"replacements": ["trailing_spaces"]}

	},
`
But pressing the hotkey didn't trigger the replacement. So, I'm wondering if I made any mistakes anywhere because I'm confused as to why it's not working.

- ST ver.: 3126
- Platform: linux
- Arch: x64
- Plugin ver.: 3.4.0
- Install via PC: True
- mdpopups ver.: 2.1.1
- backrefs ver.: 1.0.post1
- regex ver.: 2.4.124
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

**Comment by facelessuser** [comment]
1. Rules is missing the format:

    ```js
    {
        "format": "3.0",
        "replacements": {
    ```

2. Your regex will only find trailing tabs, you need to ensure a space is included in your char group `"find": "[ \\t]+$",`.

If that doesn't get it fixed, I will also need you to provide the example text you are applying this rule to.

**Comment by facelessuser** [comment]
Since I've heard nothing in this issue for over a month in response, I'll assume your issue was resolved.
