### ISSUE TITLE
Support for hotkeys

### ISSUE THREAD

**Issue by sasoriza** [facelessuser/RegReplace#65]
I found a guide that mentions including the following line within a command to allow the use of a hotkey:

"keys": ["ctrl+shift+a"],

However, this isn't working. I couldn't find anything in your documentaion, are hotkeys not / no longer supported?

- ST ver.: 3143
- Platform: windows
- Arch: x32
- Plugin ver.: 3.5.0
- Install via PC: True
- mdpopups ver.: 2.1.1
- backrefs ver.: 1.0.post1
- regex ver.: 2.4.124
- markdown ver.: 2.6.9
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

**Comment by facelessuser** [comment]
There is literally an example in the first section of the User Guide (look at the end of that sub-section): http://facelessuser.github.io/RegReplace/usage/#create-find-and-replace-sequences.

If you want me to evaluate your command, you have to post the whole command: rule you created, configured command etc.  Maybe your command isn't working because it is configured improperly.  Maybe it isn't working because the rule you created is done incorrectly. Did you check the console?  Is there an error.

Anyways, you are going to need to provide more information or I'm not going to be able to assist.

**Comment by facelessuser** [comment]
As it has been almost two weeks without any further  information posted, I am closing this issue.  If more info is provided, this issue can be reopened and I'll be happy to look into this further.

**Comment by sasoriza** [comment]
Sorry for the late reply!

These are my rules:

> {
>   "replacements": {
>     "du_to_Du": {
>       "find": "du ",
>       "replace": "Du ",
>       "greedy": true,
>       "case": true
>     },
>     "dir_to_Dir": {
>       "find": "dir ",
>       "replace": "Dir ",
>       "greedy": true,
>       "case": true
>     },
>     "dein_to_Dein": {
>       "find": "dein ",
>       "replace": "Dein ",
>       "greedy": true,
>       "case": true
>     },
>     "deine_to_Deine": {
>       "find": "deine ",
>       "replace": "Deine ",
>       "greedy": true,
>       "case": true
>     },
>     "deiner_to_Deiner": {
>       "find": "deiner ",
>       "replace": "Deiner ",
>       "greedy": true,
>       "case": true
>     },
>     "deines_to_Deines": {
>       "find": "deines ",
>       "replace": "Deines ",
>       "greedy": true,
>       "case": true
>     },
>     "deinen_to_Deinen": {
>       "find": "deinen ",
>       "replace": "Deinen ",
>       "greedy": true,
>       "case": true
>     },    
>     "deinem_to_Deinem": {
>       "find": "deinem ",
>       "replace": "Deinem ",
>       "greedy": true,
>       "case": true
>     },
>     "dich_to_Dich": {
>       "find": "dich ",
>       "replace": "Dich ",
>       "greedy": true,
>       "case": true
>     }
>   }
> }

And this is my command:

> [
>   {
>     "caption": "Reg Replace: Anrede",
>     "keys": ["ctrl+shift+o"],
>     "command": "reg_replace",
>     "args": {
>       "replacements": [
>         "du_to_Du",
>         "dir_to_Dir",
>         "dein_to_Dein",
>         "deine_to_Deine",
>         "deiner_to_Deiner",
>         "deines_to_Deines",
>         "deinen_to_Deinen",
>         "deinem_to_Deinem",
>         "dich_to_Dich",
>       ]
>     }
>   }
> ]

Using the command via command palette is working fine, but I can not assign a shortcut, I tried different ones aswell. There is no error in the console.

**Comment by facelessuser** [comment]
What is the file name that you put your command in? Key maps go in a different file than command palette commands.

**Comment by sasoriza** [comment]
Adding the command to _Default (Windows).sublime-keymap_ did the trick - thanks!

**Comment by facelessuser** [comment]
Cool. I figured that was the issue.
