### ISSUE TITLE
use selection as a part of an input for a find pattern

### ISSUE THREAD

**Issue by sergey-kritskiy** [facelessuser/RegReplace#71]
For some workflows it'd be great to have ST selection as a part of an input for a find pattern.
Thanks!

**Comment by facelessuser** [comment]
Did a little work on this today.  This is the plan:

1. The format that will be used is that of format strings.  So `r'Some value {} some [\w]+ {}'`.  Value 0 and 1 will be written in order.

    To control which selection goes where, you can explicitly set the index: `r'Some value {1} some [\w]+ {0}'`.  Or alternatively: `r'Some value {sel[1]} some [\w]+ {sel[0]}'` (`sel` is the selection list).

2. By default, the selection is just inserted into the pattern raw.  This is fine for literal searches, but for regex this is bad if your selection is something like `something(else)`, and you did not intend to for the text to be interpreted as part of the regex pattern.  So a new conversion type has been added `l` (that's lower case L) to give you literal regex characters (or escaped e.g. `something\(else\)`).  So you could use it like so: `r'Some value {1:l} some [\w]+ {0:l}'`, and the selection inputs would be escaped.

3.  For the sake of avoiding bad situations, we will limit the length of selections to the arbitrary value of 256, but his will be available as setting if you wish to increase it.  Initially, the number of allowed inputs will be limited to 10, but this will also be available in the settings to tweak.

4. Obviously this should go without saying, but this is incompatible if you have the global option `selection_only` set which will search in selection content.  Though you ignore it per command via the command option `no_selection`.  So if you are constructing a chain that uses selections, you can temporarily disable it.

So far it looks like it works pretty good.  I will hopefully have a branch up this weekend.

**Comment by facelessuser** [comment]
Maybe I'll end up hijacking `!l` for literals or instead use an property `{1.escape}`.   Still some things to think about.
