### ISSUE TITLE
Regex: First line and line of the file/view

### ISSUE THREAD

**Issue by jahan01** [facelessuser/RegReplace#72]
Hi, how do I find a pattern which is the first line and last line of the file. Searched the documentation, couldnt find any information.

**Comment by facelessuser** [comment]
By default, RegReplace uses multiline mode.  This means that `^` and `$` match the start and end (respectively) of a line.  You'll notice that Sublime's search and replace panel uses the same logic.

So to target something at the beginning of the file, you can use `\A` and for the end of the file you can use `\Z`.

You can read up on Python's `re` library syntax to learn more: https://docs.python.org/3.6/library/re.html#regular-expression-syntax.

**Comment by facelessuser** [comment]
If you have more questions related to this, feel free to reopen, but I will consider this answered.
