### ISSUE TITLE
missing dependency Pygments, won't install through Package Control

### ISSUE THREAD

**Issue by JosefTaylor** [facelessuser/RegReplace#76]
## Description

I tried to install RegReplace through Package Control, but it would not install. Console says 'pygments' could not be installed. Searching Package Control, it appears this is no longer in the directory?

## Support Info
Could not run support info command due to installation failure

## Steps to Reproduce Issue

1. Install Package Control
1. Test Package Control on another package (I tried Color Picker)
1. `Package Control: Install Package`
1. `RegReplace`

Console output:
```
Package Control: No updated packages
ignored packages updated to: ["RegReplace", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'pygments' is not currently installed; installing...
Package Control: The dependency 'pygments' is not available
Package Control: The dependency 'pygments' could not be installed or updated
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

**Comment by facelessuser** [comment]
Package control can get into weird states.  I would try again in a little bit.  Maybe restart Sublime when you are ready to have it try again.  You can verify on the Package Control repo if pygments is still specified in the dependecy.json file, and then check if that repo still exists.  If all of that is in order, this is a package control issue, and it may or may not work itself out in a little.  I can suggest some aggressive things I've used to sort out package control issues if this is still a problem.

**Comment by JosefTaylor** [comment]
I think I understand what's going on a bit better now, that Pygments is a 'dependency' rather than a 'package' in Package Control, so it doesn't show up on the web site list of packages. I'll give it another try later on, and try to get someone from PC to help me.

**Comment by JosefTaylor** [comment]
Yep, it's a problem with the Package Control crawler or something, here:
https://github.com/wbond/package_control/issues/1335

I'll close this.
