### ISSUE TITLE
Does not install from Package Control

### ISSUE THREAD

**Issue by neremin** [facelessuser/RegReplace#78]
I could not install it from the package control using the latest Sublime Text 3 build for x86. It tries to connect the server and obviously fails. Could you help me with that?

**Comment by neremin** [comment]
Seems to be Package Control issue. Posted issues to their page.

**Comment by facelessuser** [comment]
Yup, related to wbond/package_control#1334

**Comment by facelessuser** [comment]
I'm closing this as I believe the issue has been solved **and** this is an upstream issue anyways.
