### ISSUE TITLE
Multiple replace

### ISSUE THREAD

**Issue by darrengoulden-pex** [facelessuser/RegReplace#79]
## Description

Hey,

Can I configure RegReplace to replace multiple characters in one command? For example, I have this line

`  productId: 0x50 0x6f 0x6c 0x79 0x63 0x6f 0x6d 0x20 0x52 0x4d 0x58 0x35 0x30 0x30`

I want to replace all the ASCII so the result will be

`  productId: Polycom RMX500`

Results taken from https://www.rapidtables.com/code/text/ascii-table.html but currently manual

Just looking for a small example if its possible and you can point me towards one I can figure out the rest, cheers!

**Comment by facelessuser** [comment]
The easiest way would be to use a replace plugin.  That way you could target all the characters at once, and just use a Python function to convert the ASCII representations to literal characters.

Reference: http://facelessuser.github.io/RegReplace/usage/#custom-replace-plugins

**Comment by facelessuser** [comment]
If you want to chain multiple replaces together instead of using a replace plugin, you can chain replaces.  Just search the documentation for `chain`.

**Comment by darrengoulden-pex** [comment]
I'll have a look, will report back, thanks!

**Comment by darrengoulden-pex** [comment]
The chain replace is working great, faster than I expect too, thanks for the assistance!

**Comment by facelessuser** [comment]
No problem, glad you got it working.

**Comment by darrengoulden-pex** [comment]
Sorry, another question! Not sure if this is possible, checked the docs but I couldn't find the answer.

Scenario
I want to perform a replace on the two lines below, but the replacements are differenent, the first line is a character replace, second is a decimal replace, is it possible to only replace with 'char' if 'productId' exists and 'dec' if 'ip' exists?

  productId: 0x56 0x69 0x65 0x77 0x53 0x74 0x61 0x74 0x69 0x6f 0x6e 0x20 0x37 0x2e 0x30
  ip: 0x20 0x37 0x2e 0x30

**Comment by facelessuser** [comment]
With the way you are doing things, what you want would be difficult, if not impossible with a simple find and replace.  You have no context, so no way of knowing how to differently replace things.  And it would be too inefficient to look behind for each character to see if it was preceded by `productid` or `ip`. But it is possible, you just have to change how you are doing things.

I mentioned this before, but what you want is **much** easier if you use RegReplace's [`replace_plugin`](http://facelessuser.github.io/RegReplace/usage/#custom-replace-plugins) feature.

This will perform the operation in less searches and give the ability to use conditional logic.

```js
"replace_char": {
    "find": "(?i)\\b(productid|ip): ((?:0x[a-f\\d]{2} ?)+)",
    "greedy": true,
    "plugin": "User.rr_modules.replace_char"
}
```

And create a file in `Packages/User/rr_modules/replace_char.py`:

```py
char_table = {
    0: 'NUL',
    1: 'SOH'
}


def table_replace(value):
    """If character value is not in table, just convert to the character."""
    return char_table.get(value, chr(value))


def replace(m):
    """Replace 'productid` as characters and `ip` as decimal numbers."""
    use_table = m.group(1).strip().lower() == 'productid:'
    return m.group(1) + ' '.join(
        [(table_replace(int(c, 16)) if use_table else str(int(c, 16))) for c in m.group(2).strip().split(' ')]
    )
```

Command:

```js
    {
       "caption": "Reg Replace: Replace ASCII",
       "command": "reg_replace",
       "args": {
            "replacements": ["replace_char"]
        }
    }
```

You will have to play with this to get exactly what you are looking for as I don't have time to develop you a complete solution, but I feel this should be enough to get you rolling.  Sometimes, a problem is not simple enough to using *just* regular expression.

**Comment by darrengoulden-pex** [comment]
Hey Issac,

Thanks for your help with that, appreciated! I have included the final result below which works great.

Rule

```
{
	"format": "3.0",
	"replacements":
	{
		"replace_hex": { "find": "(?i)\\b(ip:|network:|productid:|versionid:) ((?:0x[a-f\\d]{1,2} ?)+)", "greedy": true, "plugin": "User.rr_modules.replace_hex" }
	}
}
```

Command

```
 {
   "caption": "Reg Replace: Replace Hex",
   "command": "reg_replace",
   "args": {
        "replacements": ["replace_hex"]
    }
 },
```

Script

```
def replace(m):
    print (m.group(1).strip().lower())
    if m.group(1).strip().lower() == 'ip:':
        return 'ip: ' + '.'.join(str(int(c, 16)) for c in m.group(2).strip().split(' '))
    if m.group(1).strip().lower() == 'network:':
        return 'network: ' + '.'.join(str(int(c, 16)) for c in m.group(2).strip().split(' '))
    if m.group(1).strip().lower() == 'productid:':
        return 'productId: ' + ''.join(chr(int(c, 16)) for c in m.group(2).strip().split(' '))
    if m.group(1).strip().lower() == 'versionid:':
        return 'versionId: ' + ''.join(chr(int(c, 16)) for c in m.group(2).strip().split(' '))
```
