### ISSUE TITLE
Commands Not Showing in Command Palette with RegReplace (Sublime Text 3)

### ISSUE THREAD

**Issue by CodeBradley** [facelessuser/RegReplace#83]
**## Description**

I already wrote this out on Stack Exchange and I'm haven't messed with GitHub so I didn't have time to figure out how to convert the formatting into GitHub syntax. Please forgive me. 

I'm trying to run a series of commands with the RegReplace plugin in Sublime Text 3 but I cannot get the command to load and I cannot get the keybindings to work either. I have no clue what's wrong.

I've tried both the old format and the 3.0 format, here is the 3.0 version:

    	{
		"format": "3.0",
		"replacements":
		{
			"extract_variables":
			{
				"find": ".*\\[(.*[^(<|>)]*?)\\].*",
				"name": "extract_variables",
				"replace": "\\1"
			}
		}
	}

**Steps Taken:**

https://stackoverflow.com/questions/50708264/commands-not-showing-in-command-palette-with-regreplace-sublime-text-3

> Run the following command from the menu: `Preferences->Package Settings->RegReplace->Support Info`.  Post the result here.

- ST ver.: 3114
- Platform: windows
- Arch: x64
- Plugin ver.: 3.8.0
- Install via PC: True
- mdpopups ver.: Version could not be acquired!
- backrefs ver.: 3.5
- regex ver.: 2.4.130
- markdown ver.: Version could not be acquired!
- pygments ver.: Version could not be acquired!
- jinja2 ver.: Version could not be acquired!

**## Steps to Reproduce Issue**

https://stackoverflow.com/questions/50708264/commands-not-showing-in-command-palette-with-regreplace-sublime-text-3

> Provide steps to reproduce the issue. Pictures are fine, but also provide code/text I can copy and paste in order to reproduce. Omit for feature requests and feature proposals.

**Comment by facelessuser** [comment]
Glad you figured it out.
