### ISSUE TITLE
Apply RegReplace to the current line only

### ISSUE THREAD

**Issue by stevekwan** [facelessuser/RegReplace#84]
Hi,

I see it's possible to apply RegReplace rules to the entire file or selected text.  Is there a way to apply a rule to the current line only?  I ask because I am using RegReplace to set up a series of shortcut hotkeys that I'd like applied to the line my cursor is on.

The closest I can get is by setting greedy:false, but this only replaces the _next_ match, which may not be at the start of the current line.

**Comment by facelessuser** [comment]
I assume you could just come up with something that highlights the current line.  Sublime comes with an "expand selection to line". You could just change that command with regreplace.  I think there is a "Chain of Command" plugin that chains commands on Package Control.

**Comment by facelessuser** [comment]
In general, I feel like this has been answered, and since there has been no response, I will consider this issue closed.

**Comment by stevekwan** [comment]
Apologies for the late response.  Thanks for your advice; I was able to come up with a workable solution by leveraging other plugins (although it isn't really ideal).

I do think this could be a useful feature, because when you are creating find/replace shortcuts you often only want to apply them to the current line.
