### ISSUE TITLE
Using RegReplace in Sublime Text 3

### ISSUE THREAD

**Issue by rbarbeito** [facelessuser/RegReplace#85]
Hello, I have this problem in the implementation of plugins, please could you help me.

[https://stackoverflow.com/questions/54537897/using-regreplace-in-sublime-text-3](https://stackoverflow.com/questions/54537897/using-regreplace-in-sublime-text-3)

**Comment by facelessuser** [comment]
I've provided an answer for you over at SO.

**Comment by rbarbeito** [comment]
Hello greetings.
I am trying with the plugins to replace `\ $` with `$` but since it is `$` part of the search commands I can not do it, you will have some suggestion

**Comment by facelessuser** [comment]
`$` is a special character in regex.  The pattern in python would usually be `re.compile(r'\\ \$')`, but you are entering this in a JSON settings file, so it is going to be `\\\\ \\$`.  Hopefully that makes sense.

**Comment by rbarbeito** [comment]
Thank you very much for your answer.
Everything was resolved using `\\\\\$`
