### ISSUE TITLE
Find first occurrence 

### ISSUE THREAD

**Issue by georgest** [facelessuser/RegReplace#87]
How can I find the first element that matches the regex? Thank you...

**Comment by facelessuser** [comment]
This is a really vague question. If you can provide more information, I might be able to answer. Please provide examples of what you are doing etc.

**Comment by georgest** [comment]
Yes, of course. If I have some opening and closing <p> elements in a html file like this:

```
<p>Some text</p>
<p>Some other text</p>
<p>Other</p>
```

I want to match only the first `p` element.

**Comment by facelessuser** [comment]
So what have you tried. What problem are you running into, or what are confused with?  I unfortunately don't have to time to provide people with complete solutions for matching, but I'm more than happy to guide people with what they may be doing wrong, clarifying confusing parts of the API, or debugging issues with the API if it is not working correctly.

**Comment by georgest** [comment]
Thanks a lot 👍
