### ISSUE TITLE
Escape '[' or ']'

### ISSUE THREAD

**Issue by tomzanger** [facelessuser/RegReplace#89]
## Description

Cannot escape literal '[' with backslash.  Tried using \\u0060 or \u0060 (not sure if this would be expected to work), but that fails as well.

Python's re documentation implies that this is the appropriate syntax: "To match a literal ']' inside a set, precede it with a backslash, or place it at the beginning of the set. For example, both [()[\]{}] and []()[{}] will both match a parenthesis." -- https://docs.python.org/3/library/re.html#regular-expression-syntax

See: ![image](https://user-images.githubusercontent.com/31482681/59795573-88936480-92a9-11e9-921d-6ff36da7150b.png)

Raw:
{
  "replacements": {
    "test square": {
      "find": "\[",
      "name": "test square",
      "replace": "great success"
    }
  }
}

**Comment by facelessuser** [comment]
You are in a JSON file. The literal string is passed to Python, so to get a literal `\` before the `[`, you have to enter it like `\\[`.

**Comment by tomzanger** [comment]
Ahh, I had tried that as well.  Thought I had saved, closed and reopened sublime, and it still failed, but I did again and it worked this time.  Must have done something wrong.  Thank you for your help, sorry for the mistake.
