### ISSUE TITLE
Unable to get trailing_spaces example to work

### ISSUE THREAD

**Issue by blackslate** [facelessuser/RegReplace#90]
## Description

I am unable to get trailing_spaces example to work. Here are the code snippets that I have added in various places.

In reg_replace_rules.sublime-settings:
```
{
    "format": "3.0",
    "replacements": 
  {
    "trailing_spaces":
    {
      "find": "[\\t ]+$]",
      "name": "trailing_spaces",
      "replace": ""   
    }
  }
}
```

In ../User/Default (Linux).sublime-keymap
```
[
  ...
  { "keys": ["ctrl+alt+space"],
     "command": "reg_replace",
     "args": {"replacements": ["trailing_spaces"]}},
]
```

In ../User/reg_replace.sublime-settings — User:
```
{ "on_save": true
, "on_save_sequences": [
    { "file_pattern": ["*"]
    , "sequence": ["trailing_spaces"]
    }
  ]
}
```

In Default.sublime-commands:
```
{ "caption": "Reg Replace: Remove Trailing Spaces"
, "command": "reg_replace"
, "args": { 
    "replacements": ["trailing_spaces"]
  }
}
```

I have tried various key bindings (including ["alt+shift+t"]), but the I cannot get the trailing spaces to disappear.

* The keyboard shortcut has no effect
* Saving a file has no effect
* I do not see a Remove Trailing Spaces command in Tools > Command Palette  

## Support Info

- ST ver.: 3207
- Platform: linux
- Arch: x64
- Plugin ver.: 3.8.0
- Install via PC: True
- mdpopups ver.: 3.4.0
- backrefs ver.: 3.5
- regex ver.: 2.4.130
- markdown ver.: 2.6.11
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

## Steps to Reproduce Issue

1. Apply the snippets that I have included above in the appropriate files
2. Add some trailing spaces to a file
3. Use the shortcut ctrl+alt+space
4. Save the file
5. Open Tools > Command Palette and type "Reg Replace" or "Remove": the command "Remove Trailing Spaces" does not appear

For what it's worth, I have successfully implemented a different command, complete with key binding, so the Reg Replace plug-in appears to be correctly installed.

**Comment by facelessuser** [comment]
```js
{
	"format": "3.0",
	"replacements":
	{
		"remove_trailing_spaces":
		{
			"find": "[ \\t]+$",
			"name": "remove_trailing_spaces",
			"replace": ""
		},
         }
}
```

```js
    {
        "caption": "Remove: Trailing Spaces",
        "command": "reg_replace",
        "args": {"replacements": ["remove_trailing_spaces"], "find_only": true}
    },
```

This works without issues for me. The only difference is I use `find_only` in the command above, but that simply highlights the targets and prompts the user whether they want to remove them or not. If I remove `find_only`, it just immediately removes the trailing spaces.

So, you would have to provide some additional info, like errors in the console, or something. Based on my testing there is no issue. Please provide more info more help.

**Comment by facelessuser** [comment]
Unfortunately this issue could not be reproduced and there was never any additional information given. Closing issue as there is nothing more I can do.

@gir-bot add S: wontfix
