### ISSUE TITLE
Is this possible?

### ISSUE THREAD

**Issue by kmiah** [facelessuser/RegReplace#91]
## Point to a different location for user rules and commands file

This is what I am trying to achieve.

I am currently creating rules and commands for 2 other users and I am currently having to constantly email them any changes I make and then they update it locally on their machine.

What I want to do is store the file on our network drive so that I can update the file in one location and the regreplace on the other users machine would point to these files on the network drive instead of their local machine which will automatically update their machine with the latest changes.

Is this possible? If so, what files would I need to update so that user rules and commands path is pointing to the network drive instead of our local machine.

Thanks
Kam

## Support Info

...

- ST ver.: 3211
- Platform: osx
- Arch: x64
- Plugin ver.: 3.8.0
- Install via PC: True
- mdpopups ver.: 3.3.3
- backrefs ver.: 3.5
- regex ver.: 2.4.130
- markdown ver.: 2.6.11
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

**Comment by facelessuser** [comment]
Unfortunately this is out of scope for what this project is intended to do. Yes there are probably ways to make sharing easier, but I leave those mechanisms up to the user to figure out and implement. I don't personally use this plugin in that way. On the rare occasion I need to share a pattern, I usually just message the person with a snippet to add to their file.
