### ISSUE TITLE
Trouble changing case

### ISSUE THREAD

**Issue by suedunham** [facelessuser/RegReplace#95]
## Description

I'm having trouble writing a replacement setting to change the case with either the re or regex engines. Perhaps the help I need is in the documentation, but the links, such as [this one](http://facelessuser.github.io/backrefs/#format-replacements) are dead. I've been writing JSON values into the appropriate files. Is this where a python plugin should be used instead?

In this case, the result of changing the case of "blotto" with `(.*)` to `\\c\\1` resulted in unicode characters "<0x01><0x01>".

## Support Info
- ST ver.: 3211
- Platform: windows
- Arch: x64
- Plugin ver.: 3.8.1
- Install via PC: True
- mdpopups ver.: 3.7.5
- backrefs ver.: 5.0
- regex ver.: 2.4.130
- markdown ver.: 3.1.1
- pygments ver.: 2.1a0
- jinja2 ver.: 2.10.1

## Steps to Reproduce Issue

User/reg_replace.sublime-settings
```
{
    "extended_back_references": true
}
```
reg-replace-rules.sublime-settings
```
{
    {"replacements": 
    {
    "uppercase":
        {
            "find": "(.*)",
            "format_replace": true,
            "name": "uppercase",
            "replace": "\\c\\1"
        }
    }
}
```
User/Default (Windows).sublime-keymap
```
[
    { "keys": ["ctrl+k", "ctrl+u"], "command": "reg_replace", "args": {
        "replacements": ["uppercase"]}
    }
]
````

> Provide steps to reproduce the issue. Pictures are fine, but also provide code/text I can copy and paste in order to reproduce. Omit for feature requests and feature proposals.

**Comment by facelessuser** [comment]
> but the links, such as this one are dead.

Whoops! Yeah, I may have restructured Backrefs documents recently...and may have broken the links here 😬 .

> In this case, the result of changing the case of "blotto" with (.*) to \\c\\1 resulted in unicode characters "<0x01><0x01>"

Okay, so this is an easy one to answer. You have `format_replace` enabled. This means that you are using format string style replacements: `r"\c{1}"` instead of `r"\c\1"`. So I would change your replace pattern to `"\\c{1}"` or turn off `format_replace`. Makes sense?

**Comment by facelessuser** [comment]
I fixed the docs, but it may take Github a little to load the new ones. I'd just click around the menu to get to navigate Backrefs docs until the new version is available. I'm missing the home page, or not pointing to the right page as the home, but it is all there.

**Comment by facelessuser** [comment]
Sorry, format replace link was dead in RegReplace document, I've fixed that references as well. So I think that fixes everything.

**Comment by facelessuser** [comment]
Hadn't realized that the bad links were also in the settings file and reported in the code. They are all now fixed. Since the question has been answered and documentation fixed, I am closing the issue.
