### ISSUE TITLE
QUESTION - Sentence case help

### ISSUE THREAD

**Issue by stephen147** [facelessuser/RegReplace#96]
Hi, I'm trying to get sentence case to work.

Here's my attempt:
```
{
  "format": "3.0",
  "replacements": {

    "case_sentence":
    {
      "find": "(^|\\.\\s+|…\\s|\\t)([a-z])",
      "replace": "\\L\\1\\C\\2",
      "greedy": true
    }

  }
}
```

**Comment by stephen147** [comment]
Got it sort by changing the settings file to:

```
{

 "extended_back_references": true // true allows the \l\1 to return the text to lowercase or others.

}
```

**Comment by facelessuser** [comment]
Glad you figured it out! Yeah, `extended_back_references` is the only way to get that functionality. It is a wrapper I wrote around the Python regular expression engine that allows you to do such things.
