### ISSUE TITLE
Clarification on duplicate "name" field in a rule

### ISSUE THREAD

**Issue by eugenesvk** [facelessuser/RegReplace#98]
## Description

I've noticed that new rules added to the `reg_replace_rules.sublime-settings` via the `Create New Regular Expression Rule` command have a duplicate name in the `"name"` field like so:
```
"aaa": { // this is the name of the command
 "find"   : "a",
 "name"   : "aaa", // this is a duplicate
 "replace": "b"
},
```

This field doesn't seem to affect anything: the commands only work when you reference the top name, not this field, so if they are different, referring to a `"name"` field doesn't work, you can also delete it, and the command keeps working
I've searched the docs for `"name"` and couldn't find anything, the examples given there also don't contain this field

Since I've just starting to use this plugin I'm a bit confused and would like to understand what the purpose of this field is

Thanks for any clarification!

## Support Info

<details>
  <summary>Support Info</summary>

  - ST ver.: 4126
  - Platform: windows
  - Arch: x64
  - Plugin ver.: 3.8.1
  - Install via PC: True
  - mdpopups ver.: 4.2.1
  - backrefs ver.: 5.0
  - regex ver.: 2.4.130
  - markdown ver.: 3.2.2
  - pygments ver.: 2.1a0
  - jinja2 ver.: 2.10.1
</details>

## Steps to Reproduce Issue

1. Invoke `Create New Regular Expression Rule` command
2. Change `name`, `find`, and `replace`, then save
3. Open `reg_replace_rules.sublime-settings` and see that a duplicate `"name"` field is added

**Comment by facelessuser** [comment]
Honestly, I think `name` is just an old artifact of how we used to do it. It should have been removed from all documentation.
